apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: appraisal-configmap-full-access
subjects:
  - kind: ServiceAccount
    name: default
    namespace: appraisal
roleRef:
  kind: ClusterRole
  name: edit
  apiGroup: rbac.authorization.k8s.io