kind: Service
apiVersion: v1
metadata:
  name: appraisal-instance1
  namespace: appraisal
spec:
  selector:
    app: appraisal-instance1
  ports:
    - name: listener
      protocol: TCP
      port: 7569
    - name: sql
      port: 1433
      targetPort: 1433
    - name: endpoint
      port: 5022
      targetPort: 5022
  clusterIP: None
---
kind: Service
apiVersion: v1
metadata:
  name: appraisal-instance2
  namespace: appraisal
spec:
  selector:
    app: appraisal-instance2
  ports:
    - name: listener
      protocol: TCP
      port: 7569
    - name: sql
      port: 1433
      targetPort: 1433
    - name: endpoint
      port: 5022
      targetPort: 5022
  clusterIP: None
---
kind: Service
apiVersion: v1
metadata:
  name: appraisal-instance3
  namespace: appraisal
spec:
  selector:
    app: appraisal-instance3
  ports:
    - name: listener
      protocol: TCP
      port: 7569
    - name: sql
      port: 1433
      targetPort: 1433
    - name: endpoint
      port: 5022
      targetPort: 5022
  clusterIP: None
---
kind: Service
apiVersion: v1
metadata:
  name: mssql-node1
  namespace: appraisal
spec:
  type: NodePort
  selector:
    app: appraisal-instance1
  ports:
  - name: sql
    protocol: TCP
    port: 1433
    targetPort: 1433
    nodePort: 31111
---
kind: Service
apiVersion: v1
metadata:
  name: mssql-node2
  namespace: appraisal
spec:
  type: NodePort
  selector:
    app: appraisal-instance2
  ports:
  - name: sql
    protocol: TCP
    port: 1433
    targetPort: 1433
    nodePort: 31112
---
kind: Service
apiVersion: v1
metadata:
  name: mssql-node3
  namespace: appraisal
spec:
  type: NodePort
  selector:
    app: appraisal-instance3
  ports:
  - name: sql
    protocol: TCP
    port: 1433
    targetPort: 1433
    nodePort: 31113
---
kind: Service
apiVersion: v1
metadata:
  name: mssql-ha
  namespace: appraisal
spec:
  clusterIP: None
  selector:
    lblabel: mssql-ha
  ports:
  - name: sql
    protocol: TCP
    port: 1433
    targetPort: 1433
---
kind: Service
apiVersion: v1
metadata:
  name: mssql-random-instance
  namespace: appraisal
spec:
  type: LoadBalancer
  selector:
    lblabel: mssql-ha
  ports:
  - name: sql
    protocol: TCP
    port: 1433
    targetPort: 1433
    nodePort: 31110
---
kind: Service
apiVersion: v1
metadata:
  name: appraisal-primary
  namespace: appraisal
spec:
  clusterIP: None
  selector:
    primary: appraisal-instance1
  ports:
  - name: sql
    protocol: TCP
    port: 1433
    targetPort: 1433
